###########################
#### Server properties ####
###########################
spring.application.name=istochnik
server.port=${SERVER_PORT}

###########################
#### Eureka properties ####
###########################
eureka.client.service-url.defaultZone=${EUREKA_URL}
eureka.client.enabled=${EUREKA_ENABLED}

############################
#### Security Properties ###
############################
security.enabled = ${SECURITY_ENABLED}
#spring.security.oauth2.resourceserver.jwt.issuer-uri = ${OAUTH2_PROVIDER_ISSUER_URI}
#spring.security.oauth2.resourceserver.jwt.jwk-set-uri = ${OAUTH2_PROVIDER_JWK_SET_URI}

######################################
### i18n / Localization Properties ###
######################################
default.language=en
default.encoding=utf8
localization.basename.messages.path=classpath:i18n/messages

############################
##### Custom Properties ####
############################
max.generation.rows.size=100000
max.generation.attempts=100
max.dictionaries.per.column=10
max.dictionary.elements.count=10000
randomizer.seed=

##############################
##### Parallel Properties ####
##############################
parallel.executor.threads-count=100
parallel.executor.queue-capacity=1000

############################
#### Logging Properties ####
############################
log.total.generation.data.benchmark.enabled=false
log.column.generation.data.benchmark.enabled=false